---
# defaults file for base_software
packages:
  - xrdp
  - tigervnc-server
  - virt-viewer
  - htop
  - dnf-automatic
  - vim
  - gedit
  - ansible
  - cockpit
  - cockpit-pcp
  - cockpit-machines
  - python3
  - code
  - google-chrome-stable
  - dnf-plugins-core
  - ansible-lint
  - python3-pip
  # - packer

services:
  - cockpit
  - pmlogger
