---
# tasks file for podman_desktop

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install "{{ flatpaks_install }}"
  community.general.flatpak:
    name: "{{ flatpaks_install }}"
    state: present
