---
- hosts: helios
  become: yes
  vars:
    packages:
    - nodejs
    - git
    - gnome-tweaks
    - nodejs

  tasks:
  
    - name: Install "{{ packages }}"
      package:  
        name:  "{{ packages }}"
        state: present
    
