---
- hosts: helios
  become: yes
  vars:
    packages:
    - nodejs
    - git
    - gnome-tweaks

  tasks:
  
    - name: Install "{{ packages }}"
      package:  
        name:  "{{ packages }}"
        state: present

# add npm module to install nodemon globally
