---
- hosts: hatchet
  become: yes
  vars:
    packages:
      - xrdp
      - tigervnc-server
      - virt-viewer
      - nodejs
      - htop
      - dnf-automatic
      - vim
      - ansible

    services:
      - xrdp
      - cockpit

  tasks:
    - name: Update everything because I have a problem
      yum:
        name: "*"
        state: latest

    - name: Install EPEL when hatchet is RHEL (codeready builder repo)
      rhsm_repository:
        name: codeready-builder-for-rhel-8-x86_64-rpms
      when: ansible_distribution == "RedHat"

    - name: Install EPEL when hatchet is RHEL (epel rpm )
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Install "{{ packages }}"
      package:
        name: "{{ packages }}"
        state: present

    - name: Enable and start "{{ services }}"
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services }}"

    - name: Enable xrdp in the firewall
      firewalld:
        port: 3389/tcp
        permanent: yes
        state: enabled
        immediate: true
