---
# tasks file for podman_desktop

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Add the podman flatpak
  community.general.flatpak_remote:
    name: podman
    state: present
