---
# tasks file for housekeeping_dirs
- name: Create housekeeping dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0770
  loop:
    - /images
    - /home/{{ user_name }}/git_projects/private
    - /home/{{ user_name }}/temp_junk
