# Notes: add vscode via snap
---
- name: Configure t14 laptop as daily driver for work
  hosts: t14
  become: true

  tasks:
    - name: Install base base_software
      ansible.builtin.import_role:
        name: base_software
      tags: base_sw

    - name: Fix airpod pro connection
      ansible.builtin.import_role:
        name: bluetooth_headphones
      tags: headphones

    - name: Configure flatpak and install sw
      ansible.builtin.import_role:
        name: flatpak_software
      tags: flatpak_software

    - name: Create housekeeping dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: andrew
        group: andrew
        mode: 0770
      loop:
        - /images
        - /home/andrew/git_projects/private
        - /home/andrew/temp_junk
