---
# defaults file for base_software
packages_install:
  - virt-viewer
  - git
  - htop
  - dnf-automatic
  - vim
  - gedit
  - ansible
  - podman
  - cockpit
  - cockpit-pcp
  - cockpit-machines
  - cockpit-podman
  - cockpit-selinux
  - python3
  - code
  - google-chrome-stable
  - dnf-plugins-core
  - ansible-lint
  - python3-pip
  - dnf-utils
  # - packer
  - gnome-extensions-app

packages_remove:
  - firefox
  - telnet

services:
  - cockpit
  - pmlogger
  - podman
