---
# tasks file for base_software
# Need to decide later if I need packer

- name: Install dnf-utils for functionality
  ansible.builtin.dnf:
    name: dnf-utils
    state: present

- name: Enable and start sshd to survive upcoming reboot
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true

- name: Update everything because I have a problem
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Check if a reboot is required
  ansible.builtin.command: needs-restarting -r
  register: reg_reboot_required
  ignore_errors: true
  failed_when: false
  changed_when: reg_reboot_required.rc != 0
  notify:
    - Reboot when needed

- name: Add the vscode repo
  ansible.builtin.yum_repository:
    name: vscode-repo
    description: vscode-repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true

- name: Add the chrome repo
  ansible.builtin.yum_repository:
    name: chrome-repo
    description: chrome-repo
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    gpgcheck: true

- name: Add the hashicorp repo
  ansible.builtin.yum_repository:
    name: hashicorp-repo
    description: hashicorp-repo
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: true

- name: Install "{{ packages_install }}"
  ansible.builtin.dnf:
    name: "{{ packages_install }}"
    state: present

- name: Enable and start "{{ services }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ services }}"

- name: Remove "{{ packages_remove }}"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages_remove }}"
